### ISSUE TITLE
请作者转载的时候注明作者

### ISSUE THREAD

**Issue by diaozxin007** [h2pl/Java-Tutorial#5]
我的若干文章被复制粘贴到了仓库，并且抹去了作者，改成了文章来自互联网。完全不尊重作者的劳动。

**Comment by h2pl** [comment]
很抱歉，请问是哪几篇文章，一定补充注明。

**Comment by h2pl** [comment]
> 我的若干文章被复制粘贴到了仓库，并且抹去了作者，改成了文章来自互联网。完全不尊重作者的劳动。

很抱歉，应该是转载的时候没有搞清楚最初的来源，请问是哪几篇文章，一定补充注明。

**Comment by diaozxin007** [comment]
https://github.com/h2pl/Java-Tutorial/blob/master/docs/cache/%E6%8E%A2%E7%B4%A2Redis%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%AE%9E%E7%8E%B010%EF%BC%9ARedis%E7%9A%84%E4%BA%8B%E4%BB%B6%E9%A9%B1%E5%8A%A8%E6%A8%A1%E5%9E%8B%E4%B8%8E%E5%91%BD%E4%BB%A4%E6%89%A7%E8%A1%8C%E8%BF%87%E7%A8%8B.md

原文：https://www.xilidou.com/2018/03/22/redis-event/

https://github.com/h2pl/Java-Tutorial/blob/master/docs/cache/%E6%8E%A2%E7%B4%A2Redis%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%AE%9E%E7%8E%B01%EF%BC%9ARedis%20%E7%9A%84%E5%9F%BA%E7%A1%80%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E6%A6%82%E8%A7%88.md

原文：https://www.xilidou.com/2018/03/12/redis-data/

**Comment by h2pl** [comment]
> https://github.com/h2pl/Java-Tutorial/blob/master/docs/cache/%E6%8E%A2%E7%B4%A2Redis%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%AE%9E%E7%8E%B010%EF%BC%9ARedis%E7%9A%84%E4%BA%8B%E4%BB%B6%E9%A9%B1%E5%8A%A8%E6%A8%A1%E5%9E%8B%E4%B8%8E%E5%91%BD%E4%BB%A4%E6%89%A7%E8%A1%8C%E8%BF%87%E7%A8%8B.md
> 
> 原文：https://www.xilidou.com/2018/03/22/redis-event/
> 
> https://github.com/h2pl/Java-Tutorial/blob/master/docs/cache/%E6%8E%A2%E7%B4%A2Redis%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%AE%9E%E7%8E%B01%EF%BC%9ARedis%20%E7%9A%84%E5%9F%BA%E7%A1%80%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E6%A6%82%E8%A7%88.md
> 
> 原文：https://www.xilidou.com/2018/03/12/redis-data/

你好，已经修改并注明来源，很抱歉给您添麻烦了，我们接下来也会进行自我纠察，避免这种情况的发生。

**Comment by diaozxin007** [comment]
> > https://github.com/h2pl/Java-Tutorial/blob/master/docs/cache/%E6%8E%A2%E7%B4%A2Redis%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%AE%9E%E7%8E%B010%EF%BC%9ARedis%E7%9A%84%E4%BA%8B%E4%BB%B6%E9%A9%B1%E5%8A%A8%E6%A8%A1%E5%9E%8B%E4%B8%8E%E5%91%BD%E4%BB%A4%E6%89%A7%E8%A1%8C%E8%BF%87%E7%A8%8B.md
> > 原文：https://www.xilidou.com/2018/03/22/redis-event/
> > https://github.com/h2pl/Java-Tutorial/blob/master/docs/cache/%E6%8E%A2%E7%B4%A2Redis%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%AE%9E%E7%8E%B01%EF%BC%9ARedis%20%E7%9A%84%E5%9F%BA%E7%A1%80%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E6%A6%82%E8%A7%88.md
> > 原文：https://www.xilidou.com/2018/03/12/redis-data/
> 
> 你好，已经修改并注明来源，很抱歉给您添麻烦了，我们接下来也会进行自我纠察，避免这种情况的发生。

为作者态度点赞。
整理资料不容易，系统的整理也不容易，感谢作者的辛勤整理。

**Comment by h2pl** [comment]
谢谢您
